### ISSUE TITLE
ballerina-examples/transactions-distributed - transactions_distributed_test is failing

### ISSUE THREAD

**Issue by SupunS** [ballerina-platform/ballerina-lang#13607]
```
Running tests
    ballerina-examples/xa-transactions:0.0.1
[ballerina/http] started HTTP/WS endpoint 172.17.0.1:35593
2019-02-13 13:22:42,869 INFO  [ballerina/transactions] - Created transaction: 05c97bf4-9aa8-4e42-a424-6aefe8f917cb 
2019-02-13 13:22:42,903 INFO  [ballerina/transactions] - Running 2-phase commit for transaction: 05c97bf4-9aa8-4e42-a424-6aefe8f917cb:ballerina-examples$xa-transactions$1 
	[pass] testFunc

	1 passing
	0 failing
	0 skipped

Generating executable
    ./target/xa-transactions.balx
Compiling source
    ballerina-examples/transactions-distributed:0.0.1

Running tests
    ballerina-examples/transactions-distributed:0.0.1
[ballerina/http] started HTTP/WS endpoint 172.17.0.1:38842
[ballerina/http] started HTTP/WS endpoint 0.0.0.0:8889
[ballerina/http] started HTTP/WS endpoint 0.0.0.0:8080
	[fail] testFunc:
	    error: Assertion Failed! {}
	    	at ballerina/test:createBallerinaError(assert.bal:42)
	    	ballerina/test:assertTrue(assert.bal:52)
	    	ballerina-examples/transactions-distributed:0.0.1:testFunc(tests/transactions_distributed_test.bal:44)

	0 passing
	1 failing
	0 skipped

[ERROR] Command execution failed.
```

**Comment by rdhananjaya** [comment]
This is fixed in https://github.com/ballerina-platform/ballerina-lang/pull/13193 [fix](https://github.com/ballerina-platform/ballerina-lang/pull/13193/files#diff-ff92e09a624e5a2806a9fc082ea15f20).

**Comment by Shan1024** [comment]
@rdhananjaya - Seems like this is not yet fixed. This occurred in https://api.travis-ci.org/v3/job/493644201/log.txt.

**Comment by MaryamZi** [comment]
Reopening since this failed again (on Travis):
```
Compiling source
    ballerina-examples/transactions-distributed:0.0.1

Running tests
    ballerina-examples/transactions-distributed:0.0.1
[ballerina/http] started HTTP/WS endpoint 172.17.0.1:34464
[ballerina/http] started HTTP/WS endpoint 0.0.0.0:8889
[ballerina/http] started HTTP/WS endpoint 0.0.0.0:8080
2019-02-26 06:19:50,358 WARN  [ballerina-examples/transactions-distributed] - Initiating transaction... 
2019-02-26 06:19:50,365 WARN  [ballerina-examples/transactions-distributed] - Created transaction: c4fd188d-d475-42e1-a2fa-7920e5221902 
2019-02-26 06:19:50,372 WARN  [ballerina-examples/transactions-distributed] - Started transaction: c4fd188d-d475-42e1-a2fa-7920e5221902:ballerina-examples$transactions-distributed$1 
2019-02-26 06:19:50,626 WARN  [ballerina-examples/transactions-distributed] - Registered local participant: 48d500c6-b162-4d49-9569-49462be0a044:ballerina-examples$transactions-distributed$2 for transaction:c4fd188d-d475-42e1-a2fa-7920e5221902 
2019-02-26 06:19:50,627 WARN  [ballerina-examples/transactions-distributed] - Received update stockquote request 
2019-02-26 06:19:50,634 WARN  [ballerina-examples/transactions-distributed] - Joined transaction: c4fd188d-d475-42e1-a2fa-7920e5221902:ballerina-examples$transactions-distributed$2 
2019-02-26 06:19:50,653 WARN  [ballerina-examples/transactions-distributed] - Update stock quote request received.
                            symbol:GOOG, price:208.77463925356386 
2019-02-26 06:19:50,697 WARN  [ballerina-examples/transactions-distributed] - Got response from bizservice 
2019-02-26 06:19:50,704 WARN  [ballerina-examples/transactions-distributed] - Running 2-phase commit for transaction: c4fd188d-d475-42e1-a2fa-7920e5221902:ballerina-examples$transactions-distributed$1 
2019-02-26 06:19:50,709 WARN  [ballerina-examples/transactions-distributed] - Sent response back to initiator 
2019-02-26 06:19:50,725 WARN  [ballerina-examples/transactions-distributed] - Preparing local participant: 48d500c6-b162-4d49-9569-49462be0a044:ballerina-examples$transactions-distributed$2 
2019-02-26 06:19:50,726 WARN  [ballerina-examples/transactions-distributed] - Local participant: 48d500c6-b162-4d49-9569-49462be0a044:ballerina-examples$transactions-distributed$2 prepared 
2019-02-26 06:19:50,744 WARN  [ballerina-examples/transactions-distributed] - Participated transaction: c4fd188d-d475-42e1-a2fa-7920e5221902:ballerina-examples$transactions-distributed$2 committed 
2019-02-26 06:19:50,748 WARN  [ballerina-examples/transactions-distributed] - Initiated transaction committed 
2019-02-26 06:19:50,759 WARN  [ballerina-examples/transactions-distributed] - messages=[["Initiating transaction...", "Created transaction: c4fd188d-d475-42e1-a2fa-7920e5221902", "Started transaction: c4fd188d-d475-42e1-a2fa-7920e5221902:ballerina-examples$transactions-distributed$1", "Registered local participant: 48d500c6-b162-4d49-9569-49462be0a044:ballerina-examples$transactions-distributed$2 for transaction:c4fd188d-d475-42e1-a2fa-7920e5221902", "Received update stockquote request", "Joined transaction: c4fd188d-d475-42e1-a2fa-7920e5221902:ballerina-examples$transactions-distributed$2", "Update stock quote request received.
                            symbol:GOOG, price:208.77463925356386", "Got response from bizservice", "Sent response back to initiator", "Running 2-phase commit for transaction: c4fd188d-d475-42e1-a2fa-7920e5221902:ballerina-examples$transactions-distributed$1", "Preparing local participant: 48d500c6-b162-4d49-9569-49462be0a044:ballerina-examples$transactions-distributed$2", "Local participant: 48d500c6-b162-4d49-9569-49462be0a044:ballerina-examples$transactions-distributed$2 prepared", "Participated transaction: c4fd188d-d475-42e1-a2fa-7920e5221902:ballerina-examples$transactions-distributed$2 committed", "Initiated transaction committed"]] 
2019-02-26 06:19:50,766 WARN  [ballerina-examples/transactions-distributed] - Sent response back to client 
	[fail] testFunc:
	    error: Assertion Failed! {}
	    	at ballerina/test:createBallerinaError(assert.bal:42)
	    	ballerina/test:assertTrue(assert.bal:52)
	    	ballerina-examples/transactions-distributed:0.0.1:testFunc(tests/transactions_distributed_test.bal:49)

	0 passing
	1 failing
	0 skipped
```

**Comment by Shan1024** [comment]
@rdhananjaya -Is it possible to treat this with the highest priority? This has caused build failures in multiple PRs.

**Comment by rdhananjaya** [comment]
This is possibly fixed with https://github.com/ballerina-platform/ballerina-lang/pull/13919
