### ISSUE TITLE
[Semantic API] Incorrect ModuleID for decimal type

### ISSUE THREAD

**Issue by shehan360** [ballerina-platform/ballerina-lang#29306]
**Description:**
Subject

**Describe your problem(s)**
1. Have the following code
```
# Holds the seconds as a decimal value.  
public type Seconds decimal;

# Test function
public function testFunc(Seconds sec) {}
```
2. Using the Semantic API get the symbol of Seconds in testFunc function. 
3. Check the `ModuleID` of the symbol. It will be of `lang.annotations`. Shouldn't it give module details of the current project? 

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by pubudu91** [comment]
Duplicate of https://github.com/ballerina-platform/ballerina-lang/issues/26284

**Comment by pubudu91** [comment]
Sorry, not exactly a duplicate, but this issue is due to the above mentioned issue. Fixing it should fix this issue too.

**Comment by pubudu91** [comment]
Checked with Chiran's PR, seems to get resolved with it.

**Comment by mohanvive** [comment]
> Checked with Chiran's PR, seems to get resolved with it.

Hmm, I don't think this issue is fixed. I am seeing the same behaviour though.

**Comment by dulajdilshan** [comment]
I think this is fixed now.

**Comment by pubudu91** [comment]
> # Holds the seconds as a decimal value.  
> public type Seconds decimal;
> 
> # Test function
> public function testFunc(Seconds sec) {}

Nope, the issue is still there. Follow the exact steps described to reproduce.

**Comment by pubudu91** [comment]
> I think this is fixed now. Now we can get the current module-id

Nope, it's still there. Follow the exact steps to reproduce.
