### ISSUE TITLE
Error when last two expressions of a conditional expression has field access.

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/ballerina-lang#33270]
Error when last two expressions of a conditional expression has field access.
Eg:
```ballerina
import ballerina/io;

type Point record {|
    int x;
    int y;
|};

public function main() {
    boolean b = true;
    Point p = { x: 2, y: 4 };
    int i = b ? p.x : p.y;
    io:println(i);
}
```

**Comment by rdulmina** [comment]
Fixed with #33270

**Comment by lochana-chathura** [comment]
Still does not work without whitespaces.

```bal
int i = b ? p.x : p.y; // works
int i = b ? p.x :p.y; // works
int i = b ? p.x: p.y; // works
int i = b ? p.x:p.y; // does not work
```

Created issue #34263 for that.
