### ISSUE TITLE
Dependant module initialization for test suite failed when building the WebSub module after updating the dependencies

### ISSUE THREAD

**Issue by TharmiganK** [ballerina-platform/ballerina-lang#37109]
**Description:**
Compiling WebSub module after updating the lang version and the dependent versions compatible with the latest lang gives a Dependant module initialization for test suite failed error.

**Steps to reproduce:**

Fails for this dependency update PR,
https://github.com/ballerina-platform/module-ballerina-websub/pull/546

Delete the `Dependancies.toml` files and run the gradle build with tests.

The following logs were printed :
```
Running Tests with Coverage

        websub
error: Dependant module initialization for test suite failed due to java.lang.ClassCastException 
{"message":"class io.ballerina.runtime.internal.types.BTypeReferenceType cannot be cast to class
 io.ballerina.runtime.api.types.SelectivelyImmutableReferenceType (io.ballerina.runtime.internal.types.
BTypeReferenceType and io.ballerina.runtime.api.types.SelectivelyImmutableReferenceType are in 
unnamed module of loader 'app')"}
        at ballerina.lang.value.0:cloneReadOnly(value.bal:58)
           ballerina.websub$test.2.tests.additional_external_error_data_test:$annot_func$_235
          (tests/additional_external_error_data_test.bal:24)
```

This is pointing to `additional_external_error_data_test` file and when the tests in this file is removed, again this error occurred pointing to the next test file 

```
Running Tests with Coverage

        websub
error: Dependant module initialization for test suite failed due to java.lang.ClassCastException 
{"message":"class io.ballerina.runtime.internal.types.BTypeReferenceType cannot be cast to class
 io.ballerina.runtime.api.types.SelectivelyImmutableReferenceType (io.ballerina.runtime.internal.types.
BTypeReferenceType and io.ballerina.runtime.api.types.SelectivelyImmutableReferenceType are in 
unnamed module of loader 'app')"}
        at ballerina.lang.value.0:cloneReadOnly(value.bal:58)
           ballerina.websub$test.2.tests.basic_subscriber_test:$annot_func$_235
           (tests/basic_subscriber_test.bal:24)
```

**Comment by HindujaB** [comment]
Closing as the fix is merged with the staging branch.

**Comment by ayeshLK** [comment]
In ballerina-distribution full build (master branch) [1] this issue still persists. Following is the error log:
```sh
error: Dependant module initialization for test 
suite failed due to java.lang.ClassCastException {"message":"class 
io.ballerina.runtime.internal.types.BTypeReferenceType cannot be cast to
 class io.ballerina.runtime.api.types.SelectivelyImmutableReferenceType 
(io.ballerina.runtime.internal.types.BTypeReferenceType and 
io.ballerina.runtime.api.types.SelectivelyImmutableReferenceType are in 
unnamed module of loader 'app')"}
        at ballerina.lang.value.0:cloneReadOnly(value.bal:58)       
ballerina.websub$test.2.tests.additional_external_error_data_test:$annot_func$_235(tests/additional_external_error_data_test.bal:24)
```

Re-opening the issue due to the above error.

[1] - [https://github.com/ballerina-platform/ballerina-release/actions/runs/3124377787/jobs/5067676666](https://github.com/ballerina-platform/ballerina-release/actions/runs/3124377787/jobs/5067676666)
