### ISSUE TITLE
Code formatting breaks with arrays inside the "match" block when using IDEA plugin

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-lang#8545]
**Description:**
When using the IDEA plugin, ballerina code formatting breaks when arrays from external packages are used as a return type inside the match block.

**Steps to reproduce:**

Please use the sample code below to reproduce the issue.

```ballerina
import wso2/jira7 as jira;

endpoint jira:Client jiraClientEP {
    clientConfig: {
        url: config:getAsString("JIRA_ENDPOINT"),
        auth: {
            scheme: "basic",
            username: config:getAsString("JIRA_USERNAME"),
            password: config:getAsString("JIRA_PASSWORD")
        }
    }
};

function getJiraProjects() returns jira:ProjectSummary[] {

    var connectorResponse = jiraClientEP->getAllProjectSummaries();
    match connectorResponse {
        //code formatting breaks due to this line
        jira7:ProjectSummary[] summaryList => return summaryList;
        jira7:JiraConnectorError e => return [];
    }
}
```

**Affected Versions:**
IDEA plugin for ballerina v0.970.0, v0.970.1, v0.970.2

**OS, DB, other environment details and versions:**
IntelliJ IDEA 2017.3.4 (Ultimate Edition)
Linux 4.13.0-41-generic

**Suggested Labels (optional):**
 plugin/intellij

**Comment by Shan1024** [comment]
Checked with the above code. Did not find any formatting issue. Seems like this issue is already fixed.

**Comment by NipunaRanasinghe** [comment]
Formatting issue seems to be fixed for the above code.  Could you please also verify the following sample code as well, since I am still getting a formatting issue with this code block.

```ballerina
import jira7 as jira;
import ballerina/http;
import ballerina/config;

endpoint jira:Client jiraClientEP {
    clientConfig: {
        url: config:getAsString("JIRA_ENDPOINT"),
        auth: {
            scheme: "basic",
            username: config:getAsString("JIRA_USERNAME"),
            password: config:getAsString("JIRA_PASSWORD")
        }
    }
};

endpoint http:Listener listener {
    port: config:getAsInt("DATA_COLLECTOR_HTTP_PORT")
};

@http:ServiceConfig {
    endpoints: [listener],
    basePath: "/service"
}

service<http:Service> fooService bind listener {

    @http:ResourceConfig {
        methods: ["GET"],
        path: "/resource"
    }
    getAllJiraProjects(endpoint caller, http:Request request) {

        http:Response response = new;

        var connectorResponse = jiraClientEP->getAllProjectSummaries();
        match connectorResponse {
            //code is properly formatted without '[]' in the following line.
            jira:ProjectSummary[] summaryList => {}
            jira:JiraConnectorError e => {}
        }
        _ = caller->respond(response);
    }
}
```

**Comment by Shan1024** [comment]
@NipunaRanasinghe - I tried the above code, seems like it formats without any issue. Can you point me exact location of the error? Please add an screenshot which shows the issue if possible.

**Comment by Shan1024** [comment]
@NipunaRanasinghe - As per the offline discussion, the issue was in package identifying logic and fixed in https://github.com/ballerina-platform/ballerina-lang/pull/8662.
